<?php

/**
 * @file
 * Contains spectra.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function spectra_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the spectra module.
    case 'help.page.spectra':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Spectral data') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function spectra_theme() {
  return [
    'spectra' => [
      'render element' => 'children',
    ],
  ];
}
